server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news_blog
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
  security:
    user:
      name: admin
      password: admin@321!^*#
      roles: ADMIN
baldur:
  app:
    jwtSecret: ======================rabindra=Spring===========================
    jwtExpirationMs: 32000